spring.application.name=school
spring.datasource.url=jdbc:postgresql://localhost:5432/mySchool
spring.datasource.username=myUser
spring.datasource.password=123
spring.jpa.hibernate.ddl=update
spring.jpa.hibernate.ddl-auto=update